services:
  satisfactory-server:
    volumes:
      - /home/phil/satisfactory-server/server-config:/config
    ports:
      - '7777:7777/tcp'
      - '7777:7777/udp'
    environment:
      - AUTOSAVENUM=2520
      - AUTOSAVEINTERVAL=15
      - MAXPLAYERS=5
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 12G
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
