services:
  satisfactory-server:
    volumes:
      - /home/phil/satisfactory-server/server-config:/config
    environment:
      - AUTOSAVENUM=2520
      - AUTOSAVEINTERVAL=15
      - MAXPLAYERS=5
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 12G
